// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44336' | (string & {});
};

export type ConfigurationResponseModel = {
    editorMode: EditorMode;
};

export type EditorMode = 'Rte' | 'Markdown';

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracorichdictionary/api/v1/configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: ConfigurationResponseModel;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];
